-- initialize
local LibStub = LibStub
local ADDON_NAME, NS = ...
local L = LibStub("AceLocale-3.0"):GetLocale(ADDON_NAME, false)
if (not L or not NS.CommFlare) then return end

-- localize stuff
local _G                                        = _G

-- epic battlegrounds
NS.CommFlare.EpicBattlegrounds = {
	["Random Epic Battleground"] = { id = 1, prefix = "EPIC" },
	["Alterac Valley"] = { id = 2, prefix = "AV" },
	["Isle of Conquest"] = { id = 3, prefix = "IOC" },
	["Battle for Wintergrasp"] = { id = 4, prefix = "WG" },
	["Wintergrasp"] = { id = 4, prefix = "WG" },
	["Ashran"] = { id = 5, prefix = "ASH" },
	["Korrak's Revenge"] = { id = 6, prefix = "KR" },
}

-- random battlegrounds
NS.CommFlare.RandomBattlegrounds = {
	["Random Battleground"] = { id = 1, prefix = "RBG" },
	["Warsong Gulch"] = { id = 2, prefix = "WSG" },
	["Arathi Basin"] = { id = 3, prefix = "AB" },
	["Deephaul Ravine"] = { id = 4, prefix = "DHR" },
	["Eye of the Storm"] = { id = 5, prefix = "EOTS" },
	["The Battle for Gilneas"] = { id = 6, prefix = "BFG" },
	["Twin Peaks"] = { id = 7, prefix = "TWP" },
	["Silvershard Mines"] = { id = 8, prefix = "SSM" },
	["Temple of Kotmogu"] = { id = 9, prefix = "TOK" },
	["Seething Shore"] = { id = 10, prefix = "SSH" },
	["Deepwind Gorge"] = { id = 11, prefix = "DWG" },
}

-- brawls
NS.CommFlare.Brawls = {
	["Brawl: Arathi Blizzard"] = { id = 1, prefix = "BLIZZ" },
	["Arathi Basin Winter"] = { id = 1, prefix = "BLIZZ" },
	["Brawl: Classic Ashran"] = { id = 2, prefix = "CLASH" },
	["Classic Ashran"] = { id = 2, prefix = "CLASH" },
	["Brawl: Comp Stomp"] = { id = 3, prefix = "COMP" },
	["Comp Stomp"] = { id = 3, prefix = "COMP" },
	["Brawl: Cooking: Impossible"] = { id = 4, prefix = "COOK" },
	["Cooking: Impossible"] = { id = 4, prefix = "COOK" },
	["Brawl: Deep Six"] = { id = 5, prefix = "DEEP" },
	["Deep Six"] = { id = 5, prefix = "DEEP" },
	["Brawl: Deepwind Dunk"] = { id = 6, prefix = "DUNK" },
	["Deepwind Dunk"] = { id = 6, prefix = "DUNK" },
	["Brawl: Gravity Lapse"] = { id = 7, prefix = "GRAV" },
	["Gravity Lapse"] = { id = 7, prefix = "GRAV" },
	["Brawl: Packed House"] = { id = 8, prefix = "PACK" },
	["Packed House"] = { id = 8, prefix = "PACK" },
	["All Arenas"] = { id = 8, prefix = "PACK" },
	["Brawl: Shado-Pan Showdown"] = { id = 9, prefix = "SHAD" },
	["Shado-Pan Showdown"] = { id = 9, prefix = "SHAD" },
	["Brawl: Southshore vs. Tarren Mill"] = { id = 10, prefix = "SSvTM" },
	["Southshore vs. Tarren Mill"] = { id = 10, prefix = "SSvTM" },
	["Brawl: Temple of Hotmogu"] = { id = 11, prefix = "BRTOH" },
	["Temple of Hotmogu"] = { id = 11, prefix = "BRTOH" },
	["Brawl: Warsong Scramble"] = { id = 12, prefix = "BRWSG" },
	["Warsong Scramble"] = { id = 12, prefix = "BRWSG" },
}

-- hearth stone spells
NS.CommFlare.HearthStoneSpells = {
	[8690] = "Hearthstone",
	[39937] = "There's No Place Like Home",
	[75136] = "Ethereal Portal",
	[94719] = "The Innkeeper's Daughter",
	[136508] = "Dark Portal",
	[171253] = "Garrison Hearthstone",
	[222695] = "Dalaran Hearthstone",
	[231504] = "Tome of Town Portal",
	[278244] = "Greatfather Winter's Hearthstone",
	[278559] = "Headless Horseman's Hearthstone",
	[285362] = "Lunar Elder's Hearthstone",
	[285424] = "Peddlefeet's Lovely Hearthstone",
	[286031] = "Noble Gardener's Hearthstone",
	[286331] = "Fire Eater's Hearthstone",
	[286353] = "Brewfest Reveler's Hearthstone",
	[298068] = "Holographic Digitalization Hearthstone",
	[308742] = "Eternal Traveler's Hearthstone",
	[326064] = "Night Fae Hearthstone",
	[342122] = "Venthyr Sinstone",
	[345393] = "Kyrian Hearthstone",
	[346060] = "Necrolord Hearthstone",
	[363799] = "Dominated Hearthstone",
	[366945] = "Enlightened Hearthstone",
	[367013] = "Broker Translocation Matrix",
	[375357] = "Timewalker's Hearthstone",
	[391042] = "Ohn'ir Windsage's Hearthstone",
	[412555] = "Path of the Naaru",
	[420418] = "Deepdweller's Earthen Hearthstone",
	[422284] = "Hearthstone of the Flame",
	[431644] = "Stone of the Hearth",
	[438606] = "Draenic Hologem",
	[463481] = "Notorious Thread's Hearthstone",
}

-- teleport spells
NS.CommFlare.TeleportSpells = {
	[556] = "Astral Recall",
	[3561] = "Teleport: Stormwind",
	[3562] = "Teleport: Ironforge",
	[3563] = "Teleport: Undercity",
	[3565] = "Teleport: Darnassus",
	[3566] = "Teleport: Thunder Bluff",
	[3567] = "Teleport: Orgrimmar",
	[23442] = "Dimensional Ripper - Everlook",
	[23453] = "Ultrasafe Transporter: Gadgetzan",
	[32271] = "Teleport: Exodar",
	[32272] = "Teleport: Silvermoon",
	[33690] = "Teleport: Shattrath",
	[35715] = "Teleport: Shattrath",
	[36890] = "Dimensional Ripper - Area 52",
	[36941] = "Ultrasafe Transporter: Toshley's Station",
	[41234] = "Teleport: Black Temple",
	[49358] = "Teleport: Stonard",
	[49359] = "Teleport: Theramore",
	[53140] = "Teleport: Dalaran - Northrend",
	[54406] = "Teleport: Dalaran",
	[66238] = "Teleport: Argent Tournament",
	[67833] = "Wormhole Generator: Northrend",
	[71436] = "Teleport: Booty Bay",
	[88342] = "Teleport: Tol Borad",
	[88344] = "Teleport: Tol Borad",
	[89157] = "Teleport: Stormwind",
	[89158] = "Teleport: Orgrimmar",
	[89597] = "Teleport: Tol Borad",
	[89598] = "Teleport: Tol Borad",
	[126755] = "Wormhole Generator: Pandaria",
	[132621] = "Teleport: Vale of Eternal Blossoms",
	[132627] = "Teleport: Vale of Eternal Blossoms",
	[145430] = "Call of the Mists",
	[163830] = "Wormhole Centrifuge",
	[175604] = "Bladespire Relic",
	[175608] = "Relic of Karabor",
	[176242] = "Teleport: Warspear",
	[176248] = "Teleport: Stormshield",
	[189838] = "Admiral's Compass",
	[193669] = "Beginner's Guide to Dimensional Rifting",
	[193759] = "Teleport: Hall of the Guardian",
	[216138] = "Emblem of Margoss",
	[220746] = "Scroll of Teleport: Ravenholdt",
	[220989] = "Teleport: Dalaran",
	[223805] = "Adept's Guide to Dimensional Rifting",
	[224869] = "Teleport: Dalaran - Broken Isles",
	[231054] = "Violet Seal of the Grand Magus",
	[250796] = "Wormhole Generator: Argus",
	[281403] = "Teleport: Boralus",
	[281404] = "Teleport: Dazar'alor",
	[289283] = "Teleport: Dazar'alor",
	[289284] = "Teleport: Boralus",
	[299083] = "Wormhome Generator: Kul Tiras",
	[299084] = "Wormhome Generator: Zandalar",
	[300047] = "Mountebank's Colorful Cloak",
	[324031] = "Wormhole Generator: Shadowlands",
	[335671] = "Scroll of Teleport: Theater of Pain",
	[344587] = "Teleport: Oribos",
	[386379] = "Wormhole Generator: Dragon Isles",
	[395277] = "Teleport: Valdrakken",
	[406714] = "Scroll of Teleport: Zskera Vaults",
	[446540] = "Teleport: Dornogal",
	[448126] = "Wormhole Generator: Khaz Algar",
}
